"""add msds register

Revision ID: 15a4cd0132bb
Revises: cb53144a1474
Create Date: 2026-08-10 11:42:08.707504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a4cd0132bb'
down_revision = 'cb53144a1474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_number', sa.String(length=30), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('src_revision', sa.String(length=20), nullable=True),
    sa.Column('src_revision_date', sa.Date(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('tel', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('use_areas', sa.String(length=300), nullable=True),
    sa.Column('storage_place', sa.String(length=120), nullable=True),
    sa.Column('ghs_class', sa.String(length=200), nullable=True),
    sa.Column('needs_lev', sa.Boolean(), nullable=True),
    sa.Column('protective_gear', sa.String(length=200), nullable=True),
    sa.Column('rsl_status', sa.String(length=20), nullable=True),
    sa.Column('rsl_note', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # (기존 테이블 FK 감지분은 이번 변경과 무관하여 제외)


def downgrade():
    op.drop_table('msds')
