"""add meeting_types and meeting_records

Revision ID: 47600f699ad5
Revises: 6275367b41be
Create Date: 2026-07-10 16:11:46.045300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47600f699ad5'
down_revision = '6275367b41be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('basis', sa.String(length=200), nullable=True),
    sa.Column('cycle', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=120), nullable=True),
    sa.Column('attendees_target', sa.String(length=200), nullable=True),
    sa.Column('agenda_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=30), nullable=True),
    sa.Column('meeting_type_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('chair', sa.String(length=120), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_type_id'], ['meeting_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_record_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['meeting_records.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # (기존 audits/capa/trainings FK 추가 감지분은 이번 변경과 무관하여 제외)


def downgrade():
    op.drop_table('meeting_record_attachments')
    op.drop_table('meeting_records')
    op.drop_table('meeting_types')
