"""add risk_improvements and attachments

Revision ID: 74c1c3eeeae3
Revises: 5e5beb84391f
Create Date: 2026-07-09 17:28:32.010975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c1c3eeeae3'
down_revision = '5e5beb84391f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_improvements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('improvement_number', sa.String(length=30), nullable=True),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('work_area', sa.String(length=100), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('hazard', sa.String(length=200), nullable=True),
    sa.Column('current_control', sa.Text(), nullable=True),
    sa.Column('before_probability', sa.Integer(), nullable=True),
    sa.Column('before_severity', sa.Integer(), nullable=True),
    sa.Column('before_level', sa.Integer(), nullable=True),
    sa.Column('before_grade', sa.String(length=10), nullable=True),
    sa.Column('improvement_plan', sa.Text(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('after_probability', sa.Integer(), nullable=True),
    sa.Column('after_severity', sa.Integer(), nullable=True),
    sa.Column('after_level', sa.Integer(), nullable=True),
    sa.Column('after_grade', sa.String(length=10), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['hse_risk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_improvement_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('improvement_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['improvement_id'], ['risk_improvements.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # (기존 audits/capa/trainings의 FK 제약 추가는 이번 변경과 무관하여 제외)


def downgrade():
    op.drop_table('risk_improvement_attachments')
    op.drop_table('risk_improvements')
