"""add 4M change management fields

Revision ID: cc152cb8fdd5
Revises: 2e525c1b5c3d
Create Date: 2026-08-18 11:25:57.993697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc152cb8fdd5'
down_revision = '2e525c1b5c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['design_changes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('dept_label', sa.String(length=30), nullable=True),
    sa.Column('reviewer_name', sa.String(length=50), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.Column('signed_by_id', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['design_changes.id'], ),
    sa.ForeignKeyConstraint(['signed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('m4_man', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('m4_machine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('m4_material', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('m4_method', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('m4_etc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('criteria_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sample_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('stock_qty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('schedule_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('doc_inspection', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('doc_process', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('doc_drawing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('doc_control', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('doc_workstd', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('doc_list', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_report', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_reliability', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_ecn', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_risk', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_none', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qa_receipt_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('qa_receiver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_eval_needed', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qa_eval_reason', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('qa_eval_items', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qa_review_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('qa_reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_result', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qa_reject_reason', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('customer_target', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_reason', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('customer_approve_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('distribution', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('change_attachments')
    op.drop_table('change_reviews')
    with op.batch_alter_table('design_changes', schema=None) as batch_op:
        for c in ['distribution','customer_approve_date','customer_name','customer_reason','customer_target',
                  'qa_reject_reason','qa_result','qa_reviewer_id','qa_review_date','qa_eval_items',
                  'qa_eval_reason','qa_eval_needed','qa_receiver_id','qa_receipt_date',
                  'test_none','test_risk','test_ecn','test_reliability','test_report','doc_list',
                  'doc_workstd','doc_control','doc_drawing','doc_process','doc_inspection',
                  'schedule_note','stock_qty','sample_date','criteria_key','m4_etc',
                  'm4_method','m4_material','m4_machine','m4_man','product_no']:
            batch_op.drop_column(c)
