"""add qualification management

Revision ID: cee823d949cc
Revises: cc152cb8fdd5
Create Date: 2026-08-21 11:07:18.468247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee823d949cc'
down_revision = 'cc152cb8fdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('procedure_doc', sa.String(length=100), nullable=True),
    sa.Column('clause', sa.String(length=100), nullable=True),
    sa.Column('target_job', sa.String(length=200), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('approver_role', sa.String(length=100), nullable=True),
    sa.Column('legal_basis', sa.String(length=200), nullable=True),
    sa.Column('record_form', sa.String(length=200), nullable=True),
    sa.Column('renewal_months', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_number', sa.String(length=30), nullable=True),
    sa.Column('qtype_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=50), nullable=False),
    sa.Column('employee_no', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('certified_date', sa.Date(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approver_name', sa.String(length=50), nullable=True),
    sa.Column('eval_score', sa.String(length=30), nullable=True),
    sa.Column('basis_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['qtype_id'], ['qualification_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('doc_kind', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('qualification_attachments')
    op.drop_table('qualifications')
    op.drop_table('qualification_types')
